spring:
  profiles.default: dev

---
spring:
  config.activate.on-profile: dev
  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
