spring:
  profiles.default: dev

  jpa.hibernate.ddl-auto: create
  datasource:
    driver-class-name: org.postgresql.Driver

---
spring:
  config.activate.on-profile: prod

---
spring:
  config.activate.on-profile: dev, test
  jpa:
    properties.hibernate:
      format_sql: true
      show-sql: true

---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres

---
spring:
  config.activate.on-profile: test
  datasource:
    username: test
    password: test
